---
- name: dnsmasq is installed
  apt:
    name: dnsmasq
    state: installed

- name: config file is present
  copy:
    src: "{{ dhcp_server_config_file }}"
    dest: /etc/dnsmasq.conf
  notify: reload dnsmasq

- name: service is enabled
  service:
    name: dnsmasq
    enabled: true

- name: service is started
  service:
    name: dnsmasq
    state: started
